//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreecoLuckyDraw.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbPreecoLuckyDrawEntities : DbContext
    {
        public DbPreecoLuckyDrawEntities()
            : base("name=DbPreecoLuckyDrawEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CAMPAIGN> CAMPAIGNs { get; set; }
        public DbSet<CAMPAIGN_DETAIL> CAMPAIGN_DETAIL { get; set; }
        public DbSet<GIFT> GIFTs { get; set; }
        public DbSet<JOINER> JOINERs { get; set; }
        public DbSet<PRIZE> PRIZEs { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<USER> USERS { get; set; }
        public DbSet<WINNER> WINNERs { get; set; }
    }
}
